name: CI - Build&Push on private registry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
          
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: registry-mds.async-agency.com/website-front
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: registry.async-agency.com/website-front:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
